; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = private.ini

[env:esp32dev]
platform = espressif32@6.6.0 ; older version supports ps4Controller library
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	pablomarquez76/PS4_Controller_Host@^1.1.1
	powerbroker2/SerialTransfer@^3.1.5

board_build.partitions = huge_app.csv
